version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: erp
      MONGO_INITDB_ROOT_PASSWORD: erp
    volumes:
      - mongo_data:/data/db
      - ./init-user-mongodb.js:/docker-entrypoint-initdb.d/init-user-mongodb.js

volumes:
  mongo_data:
